### PR TITLE
Python 3 only. New major version.

### PR DESCRIPTION
**Pull request by cobusc**

### CODE REVIEW

**Comment by DmytroLitvinov** [comment]
Any change to review that @cobusc ?

**Comment by morenoh149** [comment]
@DmytroLitvinov what do you mean?

**Comment by DmytroLitvinov** [comment]
@morenoh149 , typo error.
"Any chance to review that PR"?

**Comment by cobusc** [comment]
@DmytroLitvinov @morenoh149 I have sent you invitations to become collaborators. Then you can review. Unfortunately my spare time is limited, but I would like to get this released too.

**Comment by DmytroLitvinov** [comment]
@cobusc , have not received any of notification.

**Pull request closed without merging**
