### PR TITLE
Python 3 only. New major version.

### PR DESCRIPTION
**Pull request by cobusc**

### CODE REVIEW

**Comment by cobusc** [comment]
I closed the previous PR by mistake. Here is the new one.

**Comment by DmytroLitvinov** [comment]
I will review it later. Thanks for PR!

вс, 13 сент. 2020 г. в 13:42, Cobus Carstens <notifications@github.com>:

**Comment by DmytroLitvinov** [comment]
Hi @cobusc ,

I guess in new major version we should support only supported versions of Django.
Right now there are next versions:
* 2.2
* 3.0
* 3.1

For each Django version we should test each supported Python versions.
For example, Django 2.2 supports Python Python 3.5, 3.6, 3.7, and 3.8.
But Django 3.0 supports only 3.6, 3.7, and 3.8.

Let me know your opinion about it.

**Comment by cobusc** [comment]
@DmytroLitvinov I limited the Travis tests to only the supported configurations and updated `setup.py` as well.

**Comment by DmytroLitvinov** [comment]
Looks good :+1: 
Thanks for your efforts, @cobusc .

I guess we can merge it and provide release at PyPi?

**Comment by DmytroLitvinov** [comment]
Closes #2

**Comment by cobusc** [comment]
@DmytroLitvinov Done. Thanks for the help.

**Pull request merged**
